# gitlab scanning
include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

retire-js-dependency_scanning:
  before_script:
    - apk add autoconf libtool automake build-base gcc

# node docker image on which this would be run
image: node:12.18.4

stages:
  - test
  - deployDev

# builds app
build:
  stage: test
  script:
    - npm install
    
  tags:
    - docker

deploy:
  stage: deployDev
  script:
    - build_peerid
    - rm -rf $DOC_ROOT/*
    - cp -R build/* $DOC_ROOT
  tags:
    - peerid-runner

variables:
 SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
 GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
sonarcloud-check:
 image:
   name: sonarsource/sonar-scanner-cli:latest
   entrypoint: [""]
 cache:
   key: "${CI_JOB_NAME}"
   paths:
     - .sonar/cache
 script:
   - sonar-scanner
 when: manual
